### ISSUE TITLE
KeyError: 'left_seqs'

### ISSUE THREAD

**Issue by diegusleik** [lisiang/GREPore-seq#4]
Hi.

Congrats for this great development.

I'm trying to run the test files using the recommended command:

`python ./greporeseq/greporeseq.py all -n ./test/N26chop.fastq.gz -r ./test/N26RefInfo.yaml -d ./test/N26DemultiplexInfo.yaml`

, and I get **KeyError: 'left_seqs'**. Any advice??

`[01/17 01:15:12PM][INFO][read_input] Successful loading "Downloads/GREPore-seq-master/test/N26RefInfo.yaml"
[01/17 01:15:12PM][INFO][read_input] Successful loading "Downloads/GREPore-seq-master/test/N26DemultiplexInfo.yaml"
[01/17 01:15:12PM][INFO][greporeseq] Making FASTA file
[01/17 01:15:12PM][INFO][greporeseq] Disassembling input info
Traceback (most recent call last):
  File "/home/sequencieitor/Downloads/GREPore-seq-master/greporeseq/greporeseq.py", line 371, in <module>
    main()
  File "/home/sequencieitor/Downloads/GREPore-seq-master/greporeseq/greporeseq.py", line 338, in main
    g.disassemble()
  File "/home/sequencieitor/Downloads/GREPore-seq-master/greporeseq/greporeseq.py", line 129, in disassemble
    self.left_seqs[f'{demuti_id}'] = self.reform_seq(demuti_info['left_seqs'])
KeyError: 'left_seqs'`

**Comment by piailmitico** [comment]
I also have the same issue. Have you solved? Any help? 
thanks

**Comment by jvillanueva-cibus** [comment]
Same issue. Anyone find a resolution? Seems to a an issue with a dictionary error within the code.

**Comment by lisiang** [comment]
Sorry, I will check this problem this weekend.

**Comment by jvillanueva-cibus** [comment]
I believe I fixed the issue. The disassemble function looks for "left_seqs" and "right_seqs" from the dictionary created from the DemultiplexInfo.yaml file. However, there are no entries in that file by that name and I believe that instead this function is intended to pull the strings for "left_150bp" and the "right_150bp".

The code should change from:
self.left_seqs[f'{demuti_id}'] = self.reform_seq(demuti_info['left_seqs'])
self.right_seqs[f'{demuti_id}'] = self.reform_seq(demuti_info['right_seqs']) 

To:
self.left_seqs[f'{demuti_id}'] = self.reform_seq(demuti_info['left_150bp'])
self.right_seqs[f'{demuti_id}'] = self.reform_seq(demuti_info['right_150bp'])

The script seems to run as intended once this is updated.

I'm a little confused why the script has this bug if it was used by other groups for publication. Is there an updated script somewhere?

**Comment by piailmitico** [comment]
We had the same issue and fixed the same way without reporting it (sorry about that).
